# Generated by Django 4.2.6 on 2023-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
