# Generated by Django 4.2.6 on 2023-11-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_experience_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='workname',
            new_name='education',
        ),
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
