# Generated by Django 4.2.6 on 2023-11-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Messages',
            new_name='messages',
        ),
    ]
