# Generated by Django 4.2.6 on 2023-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_rename_messages_messages_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_percentage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
